name: Run Bats tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Run bats tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Bats tests
        uses: ffurrer2/bats-action@v1
        with:
          community: docker-cli
          args: ./test/test.bats   
