name: Run Bats tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Run bats tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Check out code and submodules
        uses: actions/checkout@v2
      - name: Checkout submodules
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive

      - name: Test
        run: ./test/bats/bin/bats test/test.bats
